import Foundation

/// Share Sheet entry: put shared text into the local Shelf vault.
/// Wire this from a Share Extension target that links `shelf-mobile`.
enum ShareExtension {
    static func putSharedText(_ text: String, home: URL) {
        // Bridge to `shelf_mobile::MobileSession::put_text` via an ObjC/Rust FFI
        // generated by the Xcode build (uniffi or a thin C header).
        let _ = (text, home)
    }
}
